# -*- coding: utf-8 -*-
"""preProcess.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lc_l7kJeLE7k54iVXw5PsNqf92MGaCEr
"""

from nltk.corpus import reuters
from nltk.corpus import stopwords
import nltk
nltk.download('reuters')
nltk.download('stopwords')
from google.colab import drive
drive.mount('/content/gdrive',force_remount=True)
dirname = '/content/gdrive/My Drive/Colab Notebooks/word2vec/google'

def preProcess():
  content = reuters.raw()
  content = content.lower()
  stop_words = stopwords.words('english')
  data = []
  sentences = content.split('\n')
  newwords = []
  for sentence in sentences:
    words = sentence.split()
    [newwords.append(word) for word in words if word not in stop_words]
  return newwords.split()

preProcess()